version: 2

jobs:
  flake8:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: pip install flake8
      - run: flake8 wagtail_localize

  prettier:
    docker:
      - image: circleci/node:14
    steps:
      - checkout:

      - type: cache-restore
        key: node-modules

      - run: npm install
      - run: npm run lint

      - type: cache-save
        key: node-modules
        paths:
          - "node_modules"

  test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: git clone git@github.com:wagtail/django-modelcluster.git
      - run: git clone git@github.com:kaedroho/wagtail.git -b internationalisation

      - type: cache-restore
        key: pip

      - run: pip install -e .[testing]
      - run: pip install ./wagtail
      - run: pip install ./django-modelcluster

      - type: cache-save
        key: pip
        paths:
          - "~/.cache/pip"

      - run: python testmanage.py test

  nightly-wagtail-test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: git clone git@github.com:wagtail/django-modelcluster.git
      - run: git clone git@github.com:kaedroho/wagtail.git -b internationalisation

      - run: pip install -e .[testing]
      - run: pip install ./wagtail
      - run: pip install ./django-modelcluster

      - run: python testmanage.py test

workflows:
    version: 2
    test:
      jobs:
        - flake8
        - prettier
        - test

    nightly:
      jobs:
        - nightly-wagtail-test
      triggers:
        - schedule:
            cron: "0 0 * * *"
            filters:
              branches:
                only:
                  - master
